[package]
name = "k_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
k256 = "0.13.3"
sha2 = "0.10.8"
tiny-keccak = { version = "2.0.0", features = ["keccak"] }
